node(edge_router,toskerliteNodesContainer,c_edge_router).
node(frontend,toskerliteNodesSoftware,c_frontend).
node(front_cont,toskerliteNodesContainer,c_front_cont).
node(front_vm,toskerliteNodesVM,c_front_vm).
node(catalogue,toskerliteNodesSoftware,c_catalogue).
node(catal_db,toskerliteNodesContainer,c_catal_db).
node(catal_cont,toskerliteNodesContainer,c_catal_cont).
node(catal_vm,toskerliteNodesVM,c_catal_vm).
node(orders,toskerliteNodesSoftware,c_orders).
node(orders_db,toskerliteNodesContainer,c_orders_db).
node(orders_cont,toskerliteNodesContainer,c_orders_cont).
node(orders_vm,toskerliteNodesVM,c_orders_vm).
node(users,toskerliteNodesSoftware,c_users).
node(users_db,toskerliteNodesContainer,c_users_db).
node(users_cont,toskerliteNodesContainer,c_users_cont).
node(users_vm,toskerliteNodesVM,c_users_vm).
node(carts,toskerliteNodesSoftware,c_carts).
node(carts_db,toskerliteNodesContainer,c_carts_db).
node(carts_cont,toskerliteNodesContainer,c_carts_cont).
node(carts_vm,toskerliteNodesVM,c_carts_vm).
node(payment,toskerliteNodesContainer,c_payment).
node(payment_vm,toskerliteNodesVM,c_payment_vm).
node(shipping,toskerliteNodesSoftware,c_shipping).
node(ship_cont,toskerliteNodesContainer,c_ship_cont).
node(rabbitmq,toskerliteNodesContainer,c_rabbitmq).
node(q_master,toskerliteNodesContainer,c_q_master).
node(ship_vm,toskerliteNodesVM,c_ship_vm).
node(bottom,bottom,c_bottom).

edge(h,edge_router,frontend).
edge(h,frontend,catalogue).
edge(h,frontend,orders).
edge(h,frontend,users).
edge(h,frontend,carts).
edge(h,frontend,payment).
edge(h,frontend,shipping).
edge(h,catalogue,catal_db).
edge(h,orders,orders_db).
edge(h,orders,users).
edge(h,orders,carts).
edge(h,orders,payment).
edge(h,orders,shipping).
edge(h,users,users_db).
edge(h,carts,carts_db).
edge(h,shipping,rabbitmq).
edge(h,q_master,rabbitmq).

edge(v,edge_router,front_vm).
edge(v,frontend,front_cont).
edge(v,front_cont,front_vm).
edge(v,catalogue,catal_cont).
edge(v,catal_db,catal_vm).
edge(v,catal_cont,catal_vm).
edge(v,orders,orders_cont).
edge(v,orders_db,orders_vm).
edge(v,orders_cont,orders_vm).
edge(v,users,users_cont).
edge(v,users_db,users_vm).
edge(v,users_cont,users_vm).
edge(v,carts,carts_cont).
edge(v,carts_db,carts_vm).
edge(v,carts_cont,carts_vm).
edge(v,payment,payment_vm).
edge(v,shipping,ship_cont).
edge(v,ship_cont,ship_vm).
edge(v,rabbitmq,ship_vm).
edge(v,q_master,ship_vm).
edge(v,front_vm,bottom).
edge(v,catal_vm,bottom).
edge(v,orders_vm,bottom).
edge(v,users_vm,bottom).
edge(v,carts_vm,bottom).
edge(v,payment_vm,bottom).
edge(v,ship_vm,bottom).
